"""PyDB Errors."""


class ConfigurationError(ValueError):
    """Raised for mal-configured database models"""
